### ISSUE TITLE
运行未生效果

### ISSUE THREAD

**Issue by jiangyd** [r455678/simple_mock#1]
我clone你的代码到本地，通过win iis运行，访问index页面添加数据（get请求，/test），数据类似你的例子，
http://127.0.0.1:5202/test?var1=1&var2=2&var3=3

但是一直返回
{
  "error": "404 Not found", 
  "msg": "fail"
}

看你的代码说是要运行mock_server.py，但是这个文件里面没有看到httpautotest类的执行

我的微信: jiangyd177 希望大神有空帮我看看

**Comment by ajbone** [comment]
他初始化插入的sql有问题，你看下数据，数据是否插入进去了。

**Comment by r455678** [comment]
@jiangyd 
抱歉，才看到。
根据你的端口，如果我没猜错的话，你请求的web的地址，应该请求server的地址。
即 http://127.0.0.1:5201/test?var1=1&var2=2&var3=3
