### ISSUE TITLE
没法打开管理页面

### ISSUE THREAD

**Issue by lunpa** [r455678/simple_mock#2]
我按照步骤把mock_server和mock_web都run起来了，但是没法打开你截图的管理页面，我看了代码貌似只有前端代码，flask也不是很懂，是不是还有一部分后端的代码没有放进去？

**Comment by r455678** [comment]
打开管理页面和后端代码没关系的，直接打开index.html啊

**Comment by lunpa** [comment]
明白了，不过我还是在mock-server加了路由，可以通过服务端打开index页面了
