### ISSUE TITLE
【Feature】如果这个server有转发到真实server的能力就完美了

### ISSUE THREAD

**Issue by yisake** [r455678/simple_mock#3]
有没有办法加个http 代理的部分啊，不匹配的请求请求到真实的server上去。

**Comment by r455678** [comment]
可以啊，无聊了写下，然后加个开关。

**Comment by yisake** [comment]
怎么写啊？大神你要加这个功能吗？

**Comment by yisake** [comment]
不知道怎么写代理的功能。。用requests那种感觉好麻烦。。

**Comment by r455678** [comment]
写好了哟~ 
配置下mock_server最上方

#如果在mock_server中没有数据是否进行转发0为是，非0为否
relay = 0
#转发服务器地址
host1 = 'http://127.0.0.1:5202'

**Comment by yisake** [comment]
哈哈哈 666
